apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: tienda-api
type: Opaque
stringData:
  # Username y password para MariaDB
  root-password: root123
  user: usuario
  password: password123
